global:
  scrape_interval: 15s #默认15s采集一次
  external_labels:
    monitor: 'go-micro-monitor'
scrape_configs:
  - job_name: 'works'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.101:9092']#从9092采集信息